
# TOML file for node configuration.

title = "Node Configuration"

# Seed number used to generate secret key set for all nodes
seed = [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]

# Node information
[[nodes]]
ip = "localhost"
port = 19392

[[nodes]]
ip = "localhost"
port = 26940

[[nodes]]
ip = "localhost"
port = 21396

[[nodes]]
ip = "localhost"
port = 14967

[[nodes]]
ip = "localhost"
port = 18333

[[nodes]]
ip = "localhost"
port = 35254

[[nodes]]
ip = "localhost"
port = 47196
