image: rust:latest

stages:
  - build

before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - mkdir -p /opt
  - 'echo "username=token\npassword=$CLOUDSMITH_ENTITLEMENT" > /opt/git-creds.sh'
  - chmod +x /opt/git-creds.sh
  - git config --global credential.helper /opt/git-creds.sh
  
build:
  stage: build
  script:
    - cargo check

    
