variables:
  FF_USE_FASTZIP: 1

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

image: registry.gitlab.com/asuran-rs/containers/rust-sccache-docker:1.56

stages:
  - lint
  - check
  - build
  - test

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

# Override git urls to use ci-job-token
before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf git://gitlab.com
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf ssh://git@gitlab.com
  - git config --global url."https://ancient123:${GITHUB_ACCESS_TOKEN}@github.com/".insteadOf git://github.com
  - git config --global url."https://ancient123:${GITHUB_ACCESS_TOKEN}@github.com/".insteadOf ssh://git@github.com
  - git config --global url."https://dl.cloudsmith.io/${CLOUDSMITH_ENTITLEMENT}/".insteadOf https://dl.cloudsmith.io/basic/
  - echo ""

lint:fmt:
  stage: lint
  tags:
    - docker
  script:
    - cargo fmt -- --check

lint:clippy:
  stage: lint
  tags:
    - docker
  script:
    - cargo clippy --workspace -- -D warnings
  cache:
    key: clippy-cache
    paths:
      - .cargo/
      - target/

lint:audit:
  stage: lint
  tags:
    - docker
  script:
    - cargo audit --ignore RUSTSEC-2020-0159 --ignore RUSTSEC-2020-0071
  cache:
    key: audit-cache
    paths:
      - .cargo/
      - target/

## Unneeded until we are exporting artifacts for other uses
#build:
#  stage: build
#  tags:
#    - docker
#  script:
#    - cargo build --workspace --release
#  cache:
#    key: build-cache
#    paths:
#      - .cargo/
#      - target/

test:
  stage: test
  tags:
    - docker
  script:
    - cargo test --workspace --release
  cache:
    key: test-cache
    paths:
      - .cargo/
      - target/

test:fuzzing:
  stage: test
  tags:
    - docker
  script:
    - cd zerok/zerok_lib; cargo fuzz run --release -s none multixfr_wallet -- -max_total_time=20m
  cache:
    key: fuzzing-cache
    paths:
      - .cargo/
      - target/
  only:
    - triggers
    - schedules
    - web
  allow_failure: true

# Currently takes over an hour to run, we wanna fix that first.
# test:extended:
#   stage: test
#   tags:
#     - docker
#   script:
#     - cargo test --release --workspace -- --ignored
#   cache:
#     key: extended-test-cache
#     paths:
#       - .cargo/
#       - target/
#   only:
#     - triggers
#     - schedules
#     - web
#   allow_failure: true

