[workspace]
members = [
    "examples/asynctide",
    "zerok/zerok_lib",
    "zerok/zerok_client",
    "zerok/zerok_validator",
    "zerok/demo1",
    "examples/demo_1",
    "examples/multi_machine",
    "examples/tideui",
    ]
[profile.dev]
opt-level = 1
