[workspace]
resolver = "2"

members = [
	"address-book",
    "examples/asynctide",
    "examples/tideui",
    "faucet",
    "validator",
    "zerok/archival_query_api",
    "zerok/nullifier_check_api",
    "zerok/validation_event_api",
    "zerok/validator_status_api",
    "zerok/zerok_client",
    "zerok/zerok_lib",
    "zerok/zerok_validator",
    ]
[profile.dev]
opt-level = 1
[profile.release]
debug = true
# lto = "thin"
