[workspace]
members = [
    "examples/asynctide",
    "examples/consensing",
    "examples/tideui",
    "zerok/counter",
    "zerok/demo1",
    "zerok/zerok_client",
    "zerok/zerok_lib",
    "zerok/zerok_validator",
    ]
