# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the Espresso library.

[meta]
NAME = "fauceet"
DESCRIPTION = "Espresso Testnet Faucet"
FORMAT_VERSION = "0.1.0"

[route.request_fee_assets]
PATH = ["/request_fee_assets"]
METHOD = "POST"
DOC = """
Request a grant of Espresso fee tokens for a given address.

The request payload should be the `UserPubKey` bundle requesting the assets, formatted as a JSON
string (starting with "USERPUBKEY").
"""
