[package]
name = "zerok_client"
version = "0.1.0"
authors = ["Joe Doyle <joe@translucence.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.10.0", features = ["unstable", "attributes"] }
async-trait = "0.1.51"
bincode = "1.3.3"
futures = "0.3.16"
jf-plonk = { features=["std"], git = "ssh://git@gitlab.com/translucence/crypto/jellyfish.git", rev = "6c88a961f6ad142501e577d91dbf39f5c58bc1f6"}
jf-primitives = { features=["std"], git = "ssh://git@gitlab.com/translucence/crypto/jellyfish.git", rev = "6c88a961f6ad142501e577d91dbf39f5c58bc1f6"}
jf-txn = { features=["std"], git = "ssh://git@gitlab.com/translucence/crypto/jellyfish.git", rev = "6c88a961f6ad142501e577d91dbf39f5c58bc1f6"}
jf-utils = { features=["std"], git = "ssh://git@gitlab.com/translucence/crypto/jellyfish.git", rev = "6c88a961f6ad142501e577d91dbf39f5c58bc1f6"}
lazy_static = "1.4.0"
rustyline = "9.0.0"
structopt = { version = "0.3", features = ["paw"] }
zerok_lib = { path = "../zerok_lib/" }
