[package]
name = "zerok_client"
version = "0.1.0"
authors = ["Joe Doyle <joe@translucence.net>"]
edition = "2018"
default-run = "zerok_client"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.10.0", features = ["unstable", "attributes"] }
async-trait = "0.1.51"
bincode = "1.3.3"
escargot = "0.5.2"
futures = "0.3.16"
jf-plonk = { features=["std"], git = "ssh://git@gitlab.com/translucence/crypto/jellyfish.git", rev = "5b500854579d58f2988ba0249b97203351a49290"}
jf-primitives = { features=["std"], git = "ssh://git@gitlab.com/translucence/crypto/jellyfish.git", rev = "5b500854579d58f2988ba0249b97203351a49290"}
jf-txn = { features=["std"], git = "ssh://git@gitlab.com/translucence/crypto/jellyfish.git", rev = "5b500854579d58f2988ba0249b97203351a49290"}
jf-utils = { features=["std"], git = "ssh://git@gitlab.com/translucence/crypto/jellyfish.git", rev = "5b500854579d58f2988ba0249b97203351a49290"}
lazy_static = "1.4.0"
rand_chacha = { version = "0.3.1", features = ["serde1"] }
regex = "1.5.4"
rpassword = "5.0.1"
rustyline = "9.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0.61"
snafu = { version = "0.6.10", features = ["backtraces"] }
shutdown_hooks = "0.1.0"
structopt = { version = "0.3", features = ["paw"] }
surf = "2.3.1"
tagged-base64 = { git = "ssh://git@gitlab.com/translucence/common/tagged-base64.git", branch = "main"}
tempdir = "0.3.7"
toml = "0.5"
zerok_lib = { path = "../zerok_lib/" }
