[package]
name = "zerok_lib"
version = "0.1.0"
authors = ["Joe Doyle <joe@translucence.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.1"
# per https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html, this should work for each project in the workspace
# however, the fact that the workspace subpath specifications do not match the expected package name may present a problem
jf-plonk = { features=["std"], git = "ssh://git@gitlab.com/translucence/crypto/jellyfish.git", rev = "3faf4400a7ae67de18400051f57afe8e4fb6d4de"}
jf-primitives = { features=["std"], git = "ssh://git@gitlab.com/translucence/crypto/jellyfish.git", rev = "3faf4400a7ae67de18400051f57afe8e4fb6d4de"}
jf-txn = { features=["std"], git = "ssh://git@gitlab.com/translucence/crypto/jellyfish.git", rev = "3faf4400a7ae67de18400051f57afe8e4fb6d4de"}
jf-utils = { features=["std"], git = "ssh://git@gitlab.com/translucence/crypto/jellyfish.git", rev = "3faf4400a7ae67de18400051f57afe8e4fb6d4de"}
phaselock = { version = "0.0.1", registry = "translucence"}
ark-std = { version = "0.2.0", default-features = false }
ark-ff = { version = "0.2.0", default-features = false }
ark-serialize = { version = "0.3.0", features = ["derive"] }
rand_chacha = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0.61"
serde_cbor = "*"
snafu = { version = "0.6.10", features = ["backtraces"] }
tagged-base64 = { git = "ssh://git@gitlab.com/translucence/common/tagged-base64.git", branch = "main"}
blake2 = "0.9.1"
bitvec = "0.21.1"
rayon = "*"
generic-array = { version = "0.14.4", features = ["serde"] }
lazy_static = "1.4.0"
bincode = "1.3.3"
async-scoped = { version = "0.7.0", features = ["use-async-std"] }
async-std = { version = "1.10.0", features = ["unstable", "attributes"] }
async-trait = "0.1.51"
async_executors = { version = "0.4.2", features = ["async_std"] }
futures = "0.3.16"
strum = "0.20"
strum_macros = "0.20.1"

[dev-dependencies]
quickcheck = "1.0"
quickcheck_macros = "1.0"
proptest = "0.8.7"
rand_xoshiro = "0.4.0"
