[package]
name = "zerok_lib"
version = "0.1.0"
authors = ["Joe Doyle <joe@translucence.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO(joe): don't do a relative path
jf-plonk = { path = "../../../jellyfish/plonk" }
jf-primitives = { path = "../../../jellyfish/primitives" }
jf-txn = { path = "../../../jellyfish/transactions" }
jf-utils = { path = "../../../jellyfish/utilities" }
ark-serialize = "0.2.0"
rand = ""
rand_chacha = "0.2.2"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
serde_cbor = "*"
blake2 = "0.9.1"
bitvec = "0.21.1"
hotstuff = { path = "../../../hotstuff/" }
rayon = "*"
generic-array = { version = "0.14.4", features = ["serde"] }
lazy_static = "1.4.0"

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"

