[package]
name = "zerok_lib"
version = "0.1.0"
authors = ["Joe Doyle <joe@translucence.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arbitrary = { version="1.0", features=["derive"] }
atomic_store = { version="0.0.2", registry="translucence" }
chacha20 = "0.8.1"
itertools = "0.10.1"
# per https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html, this should work for each project in the workspace
# however, the fact that the workspace subpath specifications do not match the expected package name may present a problem
jf-plonk = { features=["std"], git = "ssh://git@gitlab.com/translucence/crypto/jellyfish.git", rev = "787130cccdec290403e4b0f1291291f128bacd1c"}
jf-primitives = { features=["std"], git = "ssh://git@gitlab.com/translucence/crypto/jellyfish.git", rev = "787130cccdec290403e4b0f1291291f128bacd1c"}
jf-txn = { features=["std"], git = "ssh://git@gitlab.com/translucence/crypto/jellyfish.git", rev = "787130cccdec290403e4b0f1291291f128bacd1c"}
jf-utils = { features=["std"], git = "ssh://git@gitlab.com/translucence/crypto/jellyfish.git", rev = "787130cccdec290403e4b0f1291291f128bacd1c"}
# phaselock = { version = "0.0.2", registry = "translucence"}
phaselock = { git = "ssh://git@gitlab.com/translucence/systems/phaselock.git", rev = "7b01c31a4953170455d595c71ae3a3713119e5a6" }
ark-std = { version = "0.3.0", default-features = false }
ark-ff = { version = "0.3.0", default-features = false }
ark-serialize = { version = "0.3.0", features = ["derive"] }
hmac = "0.11.0"
procfs = "0.11.0"
rand_chacha = { version = "0.3.1", features = ["serde1"] }
rand = "0.7.3"
rust-argon2 = "0.8.3"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0.61"
serde_cbor = "*"
serde_with = "1.10.0"
snafu = { version = "0.6.10", features = ["backtraces"] }
tagged-base64 = { git = "ssh://git@gitlab.com/translucence/common/tagged-base64.git", branch = "main"}
threshold_crypto = "0.4.0"
sha3     = { version = "0.9.1" }
bitvec = "0.20.4"
rayon = "*"
generic-array = { version = "0.14.4", features = ["serde"] }
lazy_static = "1.4.0"
bincode = "1.3.3"
async-scoped = { version = "0.7.0", features = ["use-async-std"] }
async-std = { version = "1.10.0", features = ["unstable", "attributes"] }
async-trait = "0.1.51"
async-tungstenite = { version = "0.15.0", features = ["async-std-runtime"] }
async_executors = { version = "0.4.2", features = ["async_std"] }
futures = "0.3.16"
strum = "0.20"
strum_macros = "0.20.1"
surf = "2.3.1"
tide = "0.16.0"
tracing = "0.1.26"
zeroize = "1.3"
zerok-macros = { path = "../zerok_macros" }
hex = "0.4.3"

[dev-dependencies]
quickcheck = "1.0"
quickcheck_macros = "1.0"
proptest = "0.8.7"
rand_xoshiro = "0.4.0"
tempdir = "0.3.7"
