# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the Espresso library.

[meta]
NAME = "espresso-catchup"
DESCRIPTION = "Event streams allowing clients to replicate on-chain state changes"
FORMAT_VERSION = "0.1.0"

[route.get_events_since]
PATH = ["/get_events_since/:first", "/get_events_since/:first/:count"]
METHOD = "GET"
":first" = "Integer"
":count" = "Integer"
DOC = """
Get an ordered list of events starting at `:first`.
"""

[route.subscribe_for_events]
PATH = ["/subscribe_for_events/:first"]
METHOD = "SOCKET"
":first" = "Integer"
DOC = """
Subscribe to an ordered stream of events starting at `:first`.
"""
