# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the Espresso library.

[meta]
NAME = "espresso-metastate"
DESCRIPTION = "Auxiliary state, derived from chain state and used to build transactions"
FORMAT_VERSION = "0.1.0"

[route.check_nullifier]
PATH = ["/check_nullifier/:block_id/:nullifier"]
":block_id" = "Integer"
":nullifier" = "TaggedBase64"
DOC = """
Get a proof that a nullifier was spent or unspent after a given block.

Returns
```
{
    "spent": bool
    "proof": SetMerkleProof
}
```

`spent` indicates whether the given nullifier was spent after the block with the given index
(block 0 being the genesis block). `proof` authenticates the spent/unspent status relative to the
nullifier set root hash in the state after `block_id`.
"""
