# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the Espresso library.

[meta]
NAME = "espresso-validator"
DESCRIPTION = "HTTP interface to an Espresso validator"
FORMAT_VERSION = "0.1.0"

[route.submit]
PATH = ["/submit"]
METHOD = "POST"
DOC = """
Submit a transaction.
"""
