# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the Espresso library.

name: Windows build

on:
  push:
    branches:
      - main
      - release-*
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-2022
    steps:
      - name: Configure Git
        run: |
          git config --global url."https://ancient123:${{ secrets.ORG_GITHUB_PAT }}@github.com/".insteadOf git://github.com/
          git config --global url."https://ancient123:${{ secrets.ORG_GITHUB_PAT }}@github.com/".insteadOf ssh://git@github.com/

      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v1
        name: Enable Rust Caching

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Check
        run: cargo check --workspace --all-targets
