# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the Espresso library.

name: Code Coverage Workflow

on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  code-coverage:
    runs-on: [self-hosted, X64]
    container:
      image: ghcr.io/espressosystems/nix:main
      volumes:
        - github_nix:/nix
    timeout-minutes: 900
    steps:
      - name: Configure Git
        run: |
          git config --global url."https://ancient123:${{ secrets.ORG_GITHUB_PAT }}@github.com/".insteadOf git://github.com/
          git config --global url."https://ancient123:${{ secrets.ORG_GITHUB_PAT }}@github.com/".insteadOf ssh://git@github.com/

      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: cachix/cachix-action@v12
        with:
          name: espresso-systems-private
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Cache cargo
        uses: actions/cache@v3.0.11
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            target
          key: espresso-codecov-v1-${{ hashFiles('Cargo.lock') }}

      - name: Generate coverage reports
        run: |
          git config --global --add safe.directory "$PWD"
          nix run "github:NixOS/nix?ref=1849e6a1f64734c488c2b1469249d65ce08cef93" -- develop .#perfShell -c coverage.sh

      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info
          fail_ci_if_error: true
